#! /bin/bash

mkdir -p /mnt/sync/folders
mkdir -p /mnt/sync/config

if [ $NodeName ]; then
	sed -i "s/{NodeName}/${NodeName}/g" /mnt/sync/sync.conf
else
	sed -i 's/{NodeName}/Default/g' /mnt/sync/sync.conf
fi

exec /usr/bin/rslsync --nodaemon $*